version: '3.9'

x-volumes:
  - &project .:/var/www/
  - &project-ro .:/var/www/:ro
  - &ssh ~/.ssh/:/root/.ssh/:ro

services:
  web:
    container_name: ${APP_NAME}-web
    image: nginx:1.20-alpine
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    environment:
      - TZ=${TZ}
    volumes:
      - *project-ro
      - ./docker/conf/nginx:/etc/nginx/conf.d:ro
      - ./docker/conf/ssl:/etc/nginx/ssl:ro
      - ./docker/logs/nginx:/var/log/nginx
    restart: on-failure
    depends_on:
      - php

  php:
    container_name: ${APP_NAME}-php
    image: akarabudka/php-fpm:8.2
    environment:
      - TZ=${TZ}
    volumes:
      - *project
      - *ssh
#      - ./docker/logs/php:/var/log/php
    restart: on-failure
    user: developer:developer
    working_dir: /var/www

networks:
  default:
    name: ${APP_NAME}-network
